Use Cobra (#217)
Move to `command subcommand` structure for the sub-binaries rather than leaving compiled sources in the tree.

The root command still runs the server on execution, but leaves a warning that you should use `gcp-service-broker serve` instead.

We get `help` generated for free and `did you mean?` too, not that those are 100% necessary if this is run for you, but can be useful for testing or doing one-off admin stuff like migrating:

```
$ ./gcp-service-broker srve
Error: unknown command "srve" for "gcp-service-broker"

Did you mean this?
	serve

Run 'gcp-service-broker --help' for usage.
unknown command "srve" for "gcp-service-broker"

Did you mean this?
	serve

```

```
$ ./gcp-service-broker help
An OSB compatible service broker for Google Cloud supporting the products:

 * Database: BigTable, Cloud SQL, Datastore, Spanner
 * Storage: Cloud Storage
 * Data: ML APIs, BigQuery
 * Logging: Stackdriver

Usage:
  gcp-service-broker [flags]
  gcp-service-broker [command]

Available Commands:
  config      Show system configuration
  help        Help about any command
  migrate     Upgrade your database
  plan-info   Dump plan information from the database
  serve       Start the service broker

Flags:
      --config string   Configuration file to be read
  -h, --help            help for gcp-service-broker

Use "gcp-service-broker [command] --help" for more information about a command.

```